name: flash_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  animated_text_kit: ^1.3.0
#  firebase_core: ^0.7.0
#  firebase_auth: ^3.3.17
#  cloud_firestore: ^0.16.0+1
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  cloud_firestore: ^3.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - images/